### ISSUE TITLE
Error 404 on all tasks.

### ISSUE THREAD

**Issue by slapt** [credativUK/redmine_image_clipboard_paste#11]
Hello.

Redmine-2.5.2
Ruby 2.1.2p95
gem 2.4.1
Rails 3.2.19

When I install this plugin and try to add "New task" (or see exists tasks), I got Error 404!

   Rendered ussues/show.html.erb within layouts/base (42..8ms)
Missing template, responding with 404.
   Rendered ussues/show.html.erb within layouts/base (42..8ms)
Completed 404 Not Found in 86.6ms (...)

**Comment by pierre-pretorius** [comment]
I got the same issue, it was because I renamed the plugin to image_clipboard_paste.  When I renamed it back to redmine_image_clipboard_paste it removed this error.

**Comment by slapt** [comment]
WOW. Thank you very much. I download zip archive and directory in them called: redmine_image_clipboard_paste-master
This reason is actual and for another plugins for Redmine - thank you!
