### ISSUE TITLE
Firefox 50 - Attachment Name change to grafik.png

### ISSUE THREAD

**Issue by torben-j** [credativUK/redmine_image_clipboard_paste#29]
Hi there,

With the latest Firefox Update (Version 50), this plugin didn't work corretly anymore.
I still works with Google Chrome and Firefox < 50.

If you take a screenshot and paste it from the clipboard you will see this:

![grafik](https://cloud.githubusercontent.com/assets/10863564/21001472/bf457006-bd20-11e6-9471-5fa6f117f96f.png)

The name of the attachment is grafik.png and in the text there is !screenshot.....!

If the names match, the images would be displayed correctly.

Expected behavior:

![grafik](https://cloud.githubusercontent.com/assets/10863564/21309154/5bf97356-c5dd-11e6-80a0-d670be27a39e.png)

Thank you!
Regards JT

**Comment by u2mike** [comment]
any news to this issue?
i have the same problem since firefox update and do not want to switch to other browser :(
thanks for assisstance!
regards
michael

**Comment by torben-j** [comment]
Hi,
you can use Thorin's Fork:
https://github.com/thorin/redmine_image_clipboard_paste

The Firefox issue is already fixed in december 👍

**Comment by u2mike** [comment]
perfect ! thanks for the quick response!
